---
# https://jekyllrb.com/docs/configuration/options/

title: OpenSourceKyle
email: opensourcekyle@gmail.com
description: >-
  An open source look into my life and thoughts.
baseurl: ""
url: "https://opensourcekyle.github.io/"
github_username: OpenSourceKyle

permalink: /:categories/:year/:month/:day/:title:output_ext

remote_theme: pages-themes/modernist@v0.2.0
plugins:
  - jekyll-remote-theme  # add to the plugins list if you already have one

  # theme: minima
  # plugins:
  #   - jekyll-feed

exclude:
  - README.md

# https://jekyllrb.com/docs/collections/
collections:
  pages:
    output: true

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "pages"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "posts"
