---
# https://jekyllrb.com/docs/configuration/options/

title: OpenSourceKyle
email: opensourcekyle@gmail.com
description: >-
  An open source look into my life and thoughts.
url: "https://opensourcekyle.github.io/"
github_username: OpenSourceKyle

permalink: /:categories/:year/:month/:day/:title:output_ext

# https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll#adding-a-theme
#theme: jekyll-theme-dinky
# https://github.com/pages-themes/dinky?tab=readme-ov-file#usage
#remote_theme: pages-themes/dinky@v0.2.0
#plugins:
#  - jekyll-remote-theme

exclude:
  - README.md

# https://jekyllrb.com/docs/collections/
collections:
  pages:
    output: true

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "pages"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "posts"
