---
# https://jekyllrb.com/docs/configuration/options/

title: Kyle
email: opensourcekyle@gmail.com
description: >-
  A look into my life and head
url: "https://opensourcekyle.com"
github_username: OpenSourceKyle

permalink: /:categories/:year/:month/:day/:title:output_ext

# For Collapsible Sections using details:
# https://stackoverflow.com/a/39920717
# https://kramdown.gettalong.org/parser/kramdown.html
markdown: kramdown  # already default but for specificity
kramdown:
  parse_block_html: true

# https://github.com/OpenSourceKyle/hyde-plus-fork?tab=readme-ov-file#installation
remote_theme: OpenSourceKyle/hyde-plus-fork
author:
  name: 'Kyle'
  email:
  url:
social:
  github:
  twitter: null
  linkedin: null
  disqus: null
google_analytics:

exclude:
  - README.md

# https://jekyllrb.com/docs/collections/
collections:
  pages:
    output: true

# https://jekyllrb.com/docs/configuration/front-matter-defaults/
defaults:
  -
    scope:
      path: ""
      type: pages
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: posts
    values:
      layout: "post"
