baseURL = "http://opensourcekyle.com"
languageCode = "en-us"
title = "OpenSourceKyle"
theme = "hugo-opensourcekyle-theme"

[params]
  backgroundImage = "/images/galaxy.jpg"
  wordsPerMinute = 150  # Adjust this number to change reading speed estimate
  profileImage = "/images/myface2.jpg"
  logo = "/images/logo/logo_head.png"  # Path to your logo image
  logoWidth = "1200"  # Recommended width for social media previews
  logoHeight = "630"  # Recommended height for social media previews
  logoAlt = "OpenSourceKyle Logo"  # Alt text for accessibility and SEO
  description = "Open Source Kyle - Life is one big experiment"
  linktreeUrl = "https://linktr.ee/OpenSourceKyle"
  linktreeLogo = "/images/linktree_logo.png"  # Path relative to static folder
  pagesToShow = 6
  headerLinks = [
    { text = "About", url = "/about/" },
    { text = "Pages", url = "/pages/" },
    { text = "Blog", url = "/blog/" },
    { text = "Coaching", url = "/coaching/" },
  ]

[params.colors]
  headerText = "#ffffff"  # Crisp white for header text
  background = "#0D1B2A"  # Dark sapphire blue for a rich, modern feel
  sectionBackground = "#1B263B"  # Slightly lighter sapphire for subtle contrast
  link = "#FF4C4C"  # Vibrant crimson red for links (bold and energetic)
  linkHover = "#FF6E6E"  # Softer coral red for hover effect (adds warmth)
  paragraphText = "#eaeaea"  # Soft off-white for readability
  socialButtonBackground = "#1E2A38"  # Deep blue-gray for consistency
  warning = "#FF3B3B"  # Bold red for warnings (stands out but isn't harsh)

  # Table Colors (Normalized with Theme)
  tableBorder = "#444444"  # Dark gray for a subtle, well-defined table border
  tableHeaderBackground = "#1B263B"  # Matches section background for consistency
  tableHeaderText = "#eaeaea"  # Soft off-white for readability
  tableRowEvenBackground = "#0D1B2A"  # Same as site background for balance
  tableRowOddBackground = "#152238"  # Slight variation from even rows for distinction
  tableRowHoverBackground = "#2A3B4C"  # Lighter blue-gray for hover effect

[params.theme]
  transparency = "0.9"
  contentWidth = "600px"
  wideContentWidth = "800px"
  headerGap = "0px"  # This will be added to the navbar height
  
[frontmatter]
  date = ["date", "publishDate", ":filename", ":default"]

[permalinks]
  blog = "/blog/:year/:month/:day/:title/"
  pages = "/pages/:slug/"
  about = "/about/"
  coaching = "/coaching/"
  tags = "/tags/:slug/"
  sitemap = "/sitemap/"

[taxonomies]
  category = "categories"
  tag = "tags"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 20
  [[menu.main]]
    name = "Pages"
    url = "/pages/"
    weight = 30
  [[menu.main]]
    name = "Coaching"
    url = "/coaching/"
    weight = 40