name: Check Links

on: [push, pull_request]

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install HTML-Proofer
      run: gem install html-proofer

    - name: Run HTML-Proofer
      run: htmlproofer ./public --only-4xx --check-html
